
export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

// CATEGORIES
export const GET_CATEGORIES = "GET_CATEGORIES"
export const ADD_CATEGORY = "ADD_CATEGORY"
export const EDIT_CATEGORY = "EDIT_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"

// SUBCATEGORIES
export const GET_SUBCATEGORIES = "GET_SUBCATEGORIES"
export const ADD_SUBCATEGORY = "ADD_SUBCATEGORY"
export const EDIT_SUBCATEGORY = "EDIT_SUBCATEGORY"
export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY"

// PRODUCTS
export const GET_PRODUCTS = "GET_PRODUCTS"
export const ADD_PRODUCT = "ADD_PRODUCT"
export const EDIT_PRODUCT = "EDIT_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
